name: Release stable image

on:
  release:
    types: [published]

permissions:
  contents: read
  packages: write

env:
  CARGO_TERM_COLOR: always

jobs:
  release_image:
    strategy:
      fail-fast: false
      matrix:
        cache:
          # - memory
          - redis
          # - hybrid
          # - no-cache

    name: Release ${{ matrix.cache }} image
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      # Set up QEMU for multi-arch builds
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      # Install buildx
      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v3
      # Set buildx cache
      - name: Cache register
        uses: actions/cache@v4
        with:
          path: /tmp/.buildx-cache
          key: buildx-cache
      # Login to ghcr.io
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      # Extract branch info
      - name: Set info
        run: |
          echo "VERSION=${GITHUB_REF#refs/tags/}" >> $GITHUB_ENV
      # Print info for debug
      - name: Print Info
        run: |
          echo $VERSION
      # Create buildx multiarch
      - name: Create buildx multiarch
        run: docker buildx create --use --name=buildx-multi-arch --driver=docker-container --driver-opt=network=host
      # Modify cache variable in the dockerfile.
      - name: Modify Cache variable
        run: |
          sed -i "s/ARG CACHE=[a-z]*/ARG CACHE=redis/g" Dockerfile
      # Publish image
      - name: Publish latest
        run: |
          docker buildx build \
            --builder=buildx-multi-arch \
            --platform=linux/amd64,linux/arm64 \
            --build-arg CACHE=redis \
            --push \
            -t ghcr.io/${{ github.repository }}:latest \
            -f Dockerfile .
